name: my_ci_cd_workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest #os
    env:
      ENV_NAME: Test ENV

    steps:
    - name: Print host name
      run: echo "Host $ENV_NAME"
    - name: Print homepage URL
      run: echo "Host https://$ENV_NAME.dev"
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fixes shallow update issue when pushing to heroku
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: npm install
      run: npm install
    - name: npm build
      run: npm build --if-present
        # Build Docker image
    - name: Build Docker image
      run: |
         docker build -t teyyub392/ruzi-site:latest .

    - name: Printing docker username
      run: echo "$secrets.DOCKER_USERNAME"
      # Log in to Docker Hub
    - name: Log in to Docker Hub
#      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push teyyub392/ruzi-site:latest


