name: my_ci_cd_workflow
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest #os
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fixes shallow update issue when pushing to heroku
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: npm install
      run: |
            npm install
    - name: npm build
      run: npm build --if-present
        # Build Docker image
    - name: Build Docker image
      run: |
         docker build -t teyyub392/ruzi-site:latest .
        
        # Log in to Docker Hub
    - name: Log in to Docker Hub
#      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push teyyub392/ruzi-site:latest

